Selenium + selenide first tests added // 25.04.22
nataliashukalovich/AutomationHW pull request #1
Opened 2022-04-25 09:56 UTC by nataliashukalovich

1) Firefox getTitle and openPage

![image](https://user-images.githubusercontent.com/102675295/165066003-ed7147d4-50ea-44dc-a7b6-e972184fdf00.png)

2) Chrome getTitle and openPage

![image](https://user-images.githubusercontent.com/102675295/165066330-38ccc1e4-e85b-4262-8043-be02cb2bc9cd.png)

2022-04-25 10:06 UTC, Kirill-Simonovich requested changes

2022-04-25 10:06 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/ChromeMainPageTest.java
> +        open(catalogPage);
open() use once per test

2022-04-25 10:06 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/ChromeMainPageTest.java
> +        driver.get(mainPage);
driver.get() use once per test

2022-04-25 10:06 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/ChromeMainPageTest.java
> +        open(catalogPage);
for redirect to another page 'open()' don't use, it's wrong

2022-04-25 10:06 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/FFMainPageTest.java
> +        driver.get(newsPage);
this is work? How many windows are open?

2022-04-25 10:14 UTC, nataliashukalovich commented on src/test/java/com/stormnet/ChromeMainPageTest.java
> +        open(catalogPage);
hi @Kirill-Simonovich, I'm wondering what your comment > open() use once per test means

is it regarding not using method open() twice in the same test?

thx

2022-04-26 07:11 UTC, Kirill-Simonovich commented
Everything you wanted to implement through locators

2022-04-26 07:11 UTC, Kirill-Simonovich approved these changes

2022-04-26 07:12 UTC, nataliashukalovich commented on src/test/java/com/stormnet/FFMainPageTest.java
> +        driver.get(newsPage);
@Kirill-Simonovich yes, it works. only 1 window opens

2022-04-27 10:32 UTC, Kirill-Simonovich approved these changes
Merge

2022-04-27 10:43 UTC, merged