Test case 1
nataliashukalovich/AutomationHW pull request #2
Opened 2022-05-07 12:26 UTC by nataliashukalovich

2022-05-07 12:35 UTC, Kirill-Simonovich commented
Описание пр добавить со скринами успешного прохождения

2022-05-07 12:39 UTC, Kirill-Simonovich commented
Вы попытались применить page object pattern,либо не спешим его применять так как не прошли эту тему, либо гуглим чуть больше и применяем правильно

2022-05-07 12:50 UTC, Kirill-Simonovich requested changes

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/TestCase1.java
> +    private static final SelenideElement PRINTED_DRESS = $x("//a[@title='Printed Dress' and @class='product-name']");
Что то лишнее, можно короче

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/TestCase1.java
> +    private static final SelenideElement INFO_ACCOUNT = $x("//p[@class='info-account']");
Можно короче

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/TestCase1.java
> +    private static final String PW = "ZHB@fq86S7Kp29K";
Никогда в качестве тестовых данных не использовать личные данные

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/TestCase1.java
> +    private static final SelenideElement CONFIRM_ORDER = $x("//button[@class='button btn btn-default button-medium']");
Слишком много лишнего

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/elements/MainPageLocators.java
> +}
Зачем мне это смотреть?

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/elements/MainPageLocators.java
> +}
Зачем мне это смотреть?

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/ChromeMainPageTest.java
> +    private static final SelenideElement CATALOG_XPATH = $x("//a[@href = \"https://catalog.onliner.by\" " +
Зачем мне это проверять?

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/TestCase1.java
> +        confirmOrder();
Вот в конце обязана быть проверка, если в конце после confirm появиться сообщение об ошибке, вашему тесту будет все равно

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/TestCase1.java
> +        Assertions.assertTrue(SIGN_IN_BTN.isDisplayed(), "Main page is not opened!");
Попробуйте вставить рандомный селектор вместо валидного, сымитируем поведения когда не найдёт кнопку, попробуйте с вашей проверкой или без неё, и смотрим чем отличается

2022-05-07 12:50 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/TestCase1.java
> +        Assertions.assertEquals("Welcome to your account. Here you can manage all of your personal information" +
Хорошо

2022-05-15 19:25 UTC, Kirill-Simonovich requested changes

2022-05-15 19:25 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +    @FindBy(xpath = "//*[@type='submit']//span[.='Proceed to checkout']")
Это аннотация для pageFactory

2022-05-15 19:25 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +    @FindBy(xpath = "//*[@type='submit']//span[.='Proceed to checkout']")
А так даже работает?

2022-05-15 19:25 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +    @FindBy(xpath = "//*[@type='submit']//span[.='Proceed to checkout']")
Через $ реализовываем

2022-05-15 19:25 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +        proceedToCheckoutAdresses.shouldBe(Condition.visible).click();
Аннотация should(visible) ничего не делает здесь, в клике это ожидание уже встроенно, так что такая запись избыточна

2022-05-15 19:25 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/pages/LoginPage.java
> +        return page(MyAccountPage.class);
А что мы тут делаем?

2022-05-15 20:24 UTC, nataliashukalovich commented
![image](https://user-images.githubusercontent.com/102675295/168492459-bbd58d67-5795-45b7-a8dd-dec3b5683b04.png)

1st TC passed

2022-05-15 20:25 UTC, nataliashukalovich commented
![image](https://user-images.githubusercontent.com/102675295/168492477-d3d242e9-e59a-4f5f-9786-dc52da2837f0.png)

2nd TC passed

2022-05-16 06:01 UTC, nataliashukalovich commented on src/main/java/com/stormnet/pages/LoginPage.java
> +        return page(MyAccountPage.class);
логинимся

2022-05-16 06:01 UTC, nataliashukalovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +        proceedToCheckoutAdresses.shouldBe(Condition.visible).click();
без неё иногда не работает - сайт глючный и нужны вейтеры, либо вот так

2022-05-16 06:02 UTC, nataliashukalovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +    @FindBy(xpath = "//*[@type='submit']//span[.='Proceed to checkout']")
работает. а так нельзя?

2022-05-16 09:16 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/pages/LoginPage.java
> +        return page(MyAccountPage.class);
зачем здесь метод page

2022-05-16 09:17 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +    @FindBy(xpath = "//*[@type='submit']//span[.='Proceed to checkout']")
смысла писать так нет

2022-05-16 09:41 UTC, nataliashukalovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +    @FindBy(xpath = "//*[@type='submit']//span[.='Proceed to checkout']")
почему?

2022-05-16 09:42 UTC, nataliashukalovich commented on src/main/java/com/stormnet/pages/LoginPage.java
> +        return page(MyAccountPage.class);
здесь я инициализирую новый pageObject class

2022-05-18 10:22 UTC, Kirill-Simonovich approved these changes

2022-05-18 10:22 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +        proceedToCheckoutAdresses.shouldBe(Condition.visible).click();
shouldBe(Condition.visible, Duration.ofSecond(10)) только если так оправданно писать

2022-05-18 10:22 UTC, Kirill-Simonovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +    @FindBy(xpath = "//*[@type='submit']//span[.='Proceed to checkout']")
я на занятии объяснял, это избыточно

2022-05-18 10:30 UTC, nataliashukalovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +        proceedToCheckoutAdresses.shouldBe(Condition.visible).click();
ok

2022-05-18 10:30 UTC, nataliashukalovich commented on src/main/java/com/stormnet/pages/CartSummaryPage.java
> +    @FindBy(xpath = "//*[@type='submit']//span[.='Proceed to checkout']")
ok

2022-05-18 10:31 UTC, nataliashukalovich commented on src/test/java/com/stormnet/TestCase1.java
> +        Assertions.assertTrue(SIGN_IN_BTN.isDisplayed(), "Main page is not opened!");
ok

2022-05-18 10:31 UTC, nataliashukalovich commented on src/test/java/com/stormnet/TestCase1.java
> +        confirmOrder();
done

2022-05-18 10:31 UTC, nataliashukalovich commented on src/test/java/com/stormnet/ChromeMainPageTest.java
> +    private static final SelenideElement CATALOG_XPATH = $x("//a[@href = \"https://catalog.onliner.by\" " +
это случайно

2022-05-18 10:31 UTC, nataliashukalovich commented on src/main/java/com/stormnet/elements/MainPageLocators.java
> +}
случайно залилось

2022-05-18 10:32 UTC, nataliashukalovich commented on src/main/java/com/stormnet/elements/MainPageLocators.java
> +}
случайно залилось

2022-05-18 10:32 UTC, nataliashukalovich commented on src/test/java/com/stormnet/TestCase1.java
> +    private static final SelenideElement CONFIRM_ORDER = $x("//button[@class='button btn btn-default button-medium']");
changed

2022-05-18 10:32 UTC, nataliashukalovich commented on src/test/java/com/stormnet/TestCase1.java
> +    private static final String PW = "ZHB@fq86S7Kp29K";
ok

2022-05-18 10:32 UTC, nataliashukalovich commented on src/test/java/com/stormnet/TestCase1.java
> +    private static final SelenideElement INFO_ACCOUNT = $x("//p[@class='info-account']");
ok

2022-05-18 10:32 UTC, nataliashukalovich commented on src/test/java/com/stormnet/TestCase1.java
> +    private static final SelenideElement PRINTED_DRESS = $x("//a[@title='Printed Dress' and @class='product-name']");
ok

2022-05-18 10:36 UTC, merged