Page Object Pattern - Test Case 3
nataliashukalovich/AutomationHW pull request #3
Opened 2022-05-19 15:32 UTC by nataliashukalovich

![image](https://user-images.githubusercontent.com/102675295/169332936-8dc63d0f-6e91-47e1-b088-06adfd4037b9.png)

2022-05-19 15:51 UTC, Kirill-Simonovich approved these changes

2022-05-19 15:53 UTC, Kirill-Simonovich requested changes

2022-05-19 15:53 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/refactored/BaseTest.java
> +
в BaseTest мы настраиваем WebDriver, а данные для теста здесь лежать не должны

2022-05-20 05:42 UTC, nataliashukalovich commented on src/test/java/com/stormnet/refactored/BaseTest.java
> +
а где тогда мне хранить константы? они не подтягиваются из других классов

2022-05-20 06:55 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/refactored/BaseTest.java
> +
enum

2022-05-20 06:56 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/refactored/BaseTest.java
> +
DataTestProvider

2022-05-20 07:01 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/refactored/BaseTest.java
> +
Это информация к тест кейсам, по мере написания следующих кейсов у вас количество таких данных будет расти, и вы это все будете хранить в классе BasePage, который для этого не предназначен, он хранит в себе общую информацию для всех наших тест кейсов, а например COMMENT_TITLE нужен только для одного кейса, значит надо еще подумать где что хранить, общую информацию в BasePage, все остальное в специально предназначенных для этого классах

2022-05-20 11:45 UTC, nataliashukalovich commented on src/test/java/com/stormnet/refactored/BaseTest.java
> +
какой это должен быть класс? утилитный, или интерфейс какой-то чтобы тесты подтянули всё?

2022-05-20 12:50 UTC, Kirill-Simonovich requested changes

2022-05-20 12:50 UTC, Kirill-Simonovich commented on src/test/java/com/stormnet/refactored/BaseTest.java
> +
enum например, тестовые данные нужно хранить вместе с тестами

2022-05-20 14:52 UTC, nataliashukalovich commented on src/test/java/com/stormnet/refactored/BaseTest.java
> +
почему именно enum, и как сделать такой класс?

2022-05-21 08:42 UTC, merged